apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      tier: frontend
  template:
    metadata:
      labels:
        app: my-app
        tier: frontend
    spec:
      containers:
      - name: my-app
        image: us-central1-docker.pkg.dev/ancient-jigsaw-366112/gcp-gke-apps/python-app
        ports:
        - containerPort: 8000
        env:
          - name: ENVIRONMENT
            value: "PROD"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "8000"
          - name: REDIS_HOST
            value: "10.12.89.59"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_DB
            value: "0"