apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: my-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: my-app
    tier: frontend